Layout/FirstArrayElementIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/BlockLength:
  Enabled: False

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: False

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
