version: '3.5'

services:
  rack:
    command: bundle exec rake prod_up && bundle exec puma
    image: 18xx_rack:prod
    environment:
      RACK_ENV: production
      - DATABASE_URL

  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  # use Dockerfile to copy nginx conf into place instead of using volume
  nginx:
    build: ./nginx/
