version: '3.5'

services:
  rack:
    build: .
    depends_on:
      - db
      - redis

  queue:
    build: .
    depends_on:
      - db
      - redis

  redis:
    build: ./redis/

  db:
    build: ./db/
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
