version: '3.5'

services:
  rack:
    build: .
    depends_on:
      - db

  db:
    build: ./db/
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./log/db:/var/log/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx:/var/log/nginx
    depends_on:
      - rack
