version: '3.7'

x-zero-downtime: &zero-downtime
  deploy:
    update_config:
      order: start-first
      failure_action: rollback
      delay: 10s
    rollback_config:
      parallelism: 0
      order: stop-first
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 5
      window: 120s

services:
  rack:
    <<: *zero-downtime
    image: 18xx_rack:${RACK_TAG} # defined via ./scripts/get_image_tags.sh
    volumes:
      - ./public:/18xx/public
    healthcheck:
      test: ["CMD", "/18xx/scripts/healthcheck_rack.rb"]

  db:
    <<: *zero-downtime
    image: 18xx_postgres:${POSTGRES_TAG} # defined via ./scripts/get_image_tags.sh
    healthcheck:
      test: ["CMD", "/home/db/healthcheck_postgres.sh"]

  nginx:
    <<: *zero-downtime
    image: 18xx_nginx:${NGINX_TAG} # defined via ./scripts/get_image_tags.sh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./public:/public
      - /etc/18xxgames/ssl:/etc/18xxgames/ssl
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
