version: '3.7'

services:
  rack:
    build: .
    image: 18xx_rack:dev
    command: bash -c "bundle exec rake dev_up && bundle exec rerun --background -i 'build/*' -i 'public/*' 'puma'"
    ports:
      - 9292:9292
    volumes:
      - .:/18xx
    depends_on:
      - db

  db:
    build: .
    image: 18xx_postgres:dev

  adminer:
    image: adminer
    ports:
      - 8080:8080
