version: '3.7'

services:
  rack:
    env_file: .env
    volumes:
      - ./log/rack:/18xx/log/rack

  db:
    env_file: .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./log/db:/var/log/postgresql
