version: '3.5'

x-rack: &rack
  image: 18xx_rack:dev
  environment:
    DATABASE_URL: postgres://root:password@db:5432/18xx_development
    RACK_ENV: development
    RUBYOPTS: --yjit
  build:
    args:
      RACK_ENV: development
  volumes:
    - .:/18xx:z
    - /18xx/vendor
  depends:
    - db
    - redis

services:
  rack:
    <<: *rack
    ports:
      - 9292:9292

  queue:
    <<: *rack
    command: bundle exec ruby queue.rb # bundle exec rerun --background -i 'build/*' -i 'public/*' 'ruby queue.rb'

  db:
    build:
      context: ./db/
    volumes:
      - ./db/data:/var/lib/postgresql/data:Z
    ports:
      - 127.0.0.1:5433:5432
    logging:
      options:
        max-size: "10m"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 18xx_development
