version: '3.5'

services:
  rack:
    environment:
      RUBYOPTS: --jit
    build: .
    depends_on:
      - db

  queue:
    build: .
    depends_on:
      - db
      - rack

  db:
    build: ./db/
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5433:5432
