bank:
  cash: 7000

phases:
  - train: 2
    limit: 4
    tile: yellow
    rounds:
      - type: stock
      - type: operating
  - train: 3
    limit: 4
    tile: green
    rounds:
      - type: stock
      - type: operating
        count: 2
  - train: 4
    limit: 3
    tile: green
    rounds:
      - type: stock
      - type: operating
        count: 2
  - train: 5
    limit: 2
    tile: brown
    rounds:
      - type: stock
      - type: operating
        count: 3
  - train: D
    limit: 2
    tile: gray
    rounds:
      - type: stock
      - type: operating
        count: 3

trains:
  - type: 2
    cost: 80
    count: 6
    rust:
      train: 4
  - type: 3
    cost: 180
    count: 5
    rust:
      train: 6
  - type: 4
    cost: 300
    count: 4
    rust:
      train: D
  - type: 5
    cost: 450
    count: 3
  - type: 6
    cost: 630
    count: 2
  - type: D
    cost: 1100
    discount:
      amount: 400
      type: trade
      trains:
        - 4
        - 5
        - 6
    available:
      type: purchase
      train: 6

corporations:
  - name: Awa Railroad
    symbol: AR
    tokens: 2
  - name: Iyo Railway
    symbol: IR
    tokens: 2
  - name: Sanuki Railway
    symbol: SR
    tokens: 2
  - name: Takamatsu & Kotohira Electric Railway
    symbol: KO
    tokens: 2
  - name: Tosa Electric Railway
    symbol: TR
    tokens: 3
  - name: Tosa Kuroshio Railway
    symbol: KU
    tokens: 1
  - name: Uwajima Railway
    symbol: UR
    tokens: 3

companies:
  - name: Takamatsu E-Railroad
    cost: 20
    income: 5
    abilities:
      - block:
          hex: K4
  - name: Mitsubishi Ferry
    cost: 30
    income: 5
    abilities:
      - lay:
          time:
            not:
              round: operating
              turn: other
          tile: 437
          hexes:
            - B11
            - G10
            - I12
            - J9
  - name: Ehime Railway
    cost: 40
    income: 10
    abilities:
      - lay:
          tile: green
          hex: C4
  - name: Sumitomo Mines Railway
    cost: 50
    income: 15
    abilities:
      - lay:
          discount:
            terrain: mountain
  - name: Duogo Railway
    cost: 60
    income: 15
    abilities:
      - exchange:
          share:
            corporation: IR
            percent: 10
  - name: South Iyo Railway
    cost: 80
    income: 20
    players:
      - 3
      - 4
      - 5
  - name: Uno-Takamatsu Ferry
    cost: 150
    income: 30
    players:
      - 4
      - 5
